# Site settings
title: Cyan's Blog
email: 6115119@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Cyan's Blog
baseurl: "" # the subpath of your site, e.g. if value is '/blog', Home is pages.github.io/blog/
url: "https://cyal1.github.io" # the base hostname & protocol for your site
twitter_username: cyan
github_username: cyan
background_color: '#fff'
text_color: '#454545'
link_color: '#00B2EE'
# font_family: '微软雅黑'
font_family: '"PT Sans", Helvetica, Arial, sans-serif'
banner: 只有非常努力，才能看起来毫不费力!

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
social-links:
  - name: Weixin
    url: http://weixin.qq.com
    icon: fab fa-weixin
    color: "#51aa38"
    external: true
  - name: QQ
    url: https://im.qq.com
    icon: fab fa-qq
    color: "#54b5ef"
    external: true
  - name: GitHub
    url: http://github.com/cyal1
    icon: fab fa-github
    color: "#666666"
    external: true
  - name: Weibo
    url: https://www.weibo.com
    icon: fab fa-weibo
    color: "#d33337"
    external: true
  - name: Alipay
    url: https://www.alipay.com
    icon: fab fa-alipay
    color: "#3778f6"
    external: true
  - name: Email
    url: mailto:6115119@qq.com
    icon: fas fa-envelope
    color: "#c24a3a"
    external: true
  - name: RSS
    url: https://localhost/feed.xml
    icon: fas fa-rss
    color: "#ee802f"
    external: true


redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
plugins:
  - jekyll-redirect-from
sass:
    style: compressed
# layout: compress
